server:
  port: 8002

spring:
  application:
    name: bc-ms-user
    verification-url: http://${HOST_IP:localhost}:8001/users/verify
  datasource:
    url: jdbc:postgresql://${HOST_IP:localhost}:5432/${DB_NAME:bestcommerce}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    tomcat:
      initial-size: 5
      max-wait: 60000
      max-active: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
      ribbon:
        enable: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${HOST_IP:localhost}:8761/eureka
